### ISSUE TITLE
[SOLVED] Error that i cant solve, cant create config file. I followed strictly all the steps and used all correct versions of Python. 

### ISSUE THREAD

**Issue by thebrainiak** [cisagov/untitledgoosetool#16]
# 🐛 Summary #
I used Windows 10, with python 3.9, and tried with 3.8 too. With linux debian i have the same error.

I followed all the steps and using the version of python that they recommend, to run the file generate_conf.py nothing appears, and when I try to run goosey or gossey-gui I get this error:

I have all the modules installed because i followed all the steps correctly, and all is added correctly to the Path, i cant understand whats happening. Can you help me? Thank you.

I followed all the strictly all the steps and installed all the dependencies, and i cant understand whats happening, Thank you!

1. python -m venv .venv
.venv\Scripts\activate
2. git clone https://github.com/cisagov/untitledgoosetool.git
cd untitledgoosetool
python3 -m pip install . 
3. python3 scripts/generate_conf.py
## Expected behavior ##

What did you expect to happen that didn't?

Generate the config file

## Any helpful log output or screenshots ##

Paste the results here:

```console
Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in run_module_as_main return run_code(code, main_globals, None, File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in run_code exec(code, run_globals) File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\goosey-gui.exe_main.py", line 4, in File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\goosey\guimain.py", line 8, in from goosey.main import main as gooseymain File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\goosey\main.py", line 10, in from goosey.auth import Authentication File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\goosey\auth.py", line 19, in from seleniumwire import webdriver File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\webdriver.py", line 28, in from seleniumwire import backend, utils File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\backend.py", line 4, in from seleniumwire.server import MitmProxy File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\server.py", line 5, in from seleniumwire.handler import InterceptRequestHandler File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\handler.py", line 5, in from seleniumwire import har File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\har.py", line 12, in from seleniumwire.thirdparty.mitmproxy.http import HTTPFlow File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\thirdparty\mitmproxy\http.py", line 7, in from seleniumwire.thirdparty.mitmproxy.net import http File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\thirdparty\mitmproxy\net\http_init.py", line 1, in from seleniumwire.thirdparty.mitmproxy.net.http import http1, http2, multipart, status_codes File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1_init.py", line 2, in from .read import (connection_close, expected_http_body_size, read_body, read_request, read_request_head, File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 7, in from seleniumwire.thirdparty.mitmproxy.net.http import (headers, request, File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\request.py", line 8, in from seleniumwire.thirdparty.mitmproxy.net.http import cookies, message, multipart File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 6, in from seleniumwire.thirdparty.mitmproxy.net.http import encoding File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 12, in import brotli File "C:\Users\cyber\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\brotli.py", line 8, in import _brotli ImportError: DLL load failed while importing _brotli: Cannot find the specified module.
```

Add any screenshots of the problem here.

@victoriawallace-cisa @h-m-f-t @sangling  Thank you for your answers! Best regards. Hope you will help me.
![ERRORGOOSEY](https://user-images.githubusercontent.com/101867702/228900216-0c8e5ba4-73b1-4782-a04b-26c179aaad27.jpg)

**Comment by victoriawallace-cisa** [comment]
Can you try to do the following:

```
pip uninstall brotli
pip install brotli
```

**Comment by thebrainiak** [comment]
> Can you try to do the following:
> 
> ```
> pip uninstall brotli
> pip install brotli
> ```

SOLVED it was a  C++ runtime error? is it possible? im using a new virtual machine and i had to install it, thank you!

**Comment by victoriawallace-cisa** [comment]
Thanks for letting us know about the solution.
